version: 2
plan:
  project-key: AL
  key: PLAN
  name: Genrated

stages:
  - Compile:
      jobs:
        - Test

Test:
  tasks:
    - script:
        - ./gradlew clean test

other:
  concurrent-build-plugin: system-default
  custom:
    allure:
      server:
        token: 123123123123
        endpoint: httpasdaklsjd
